services:
  - type: web
    name: chatx
    runtime: python
    rootDir: backend
    buildCommand: "bash build.sh"
    startCommand: "gunicorn -t 120 app:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: ALLOWED_ORIGINS
        value: "*,https://chat-oisandgcv-shivamsinghtomar78s-projects.vercel.app,https://chat-hsc8qgfca-shivamsinghtomar78s-projects.vercel.app"
